FROM node:14-alpine

WORKDIR /app

COPY package.json ./

RUN npm install --registry=https://registry.npmmirror.com

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npx", "http-server", "manage", "-p", "3000"]
