FROM node:14-alpine

RUN npm config set registry https://registry.npmmirror.com

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8003

CMD ["npm", "run", "dev"]
